Quiet test run and make passing tests more obvious.
Still lots of warnings but it's better.

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -5,7 +5,6 @@ cd "`dirname \"$0\"`/.."
 mvn package
 
 cd test
-echo "compiling test class..."
 
 compile_and_run() {
   base_name=`basename -s .java $1`
@@ -15,14 +14,18 @@ compile_and_run() {
     cap_base_name=$base_name
   fi
   javac -classpath .:"../target/swagger-java-client-1.0.0.jar" $cap_base_name.java
-  echo "running tests"
   java -classpath .:"../target/swagger-java-client-1.0.0.jar":"../target/lib/*" $cap_base_name
+}
+
+# runs a test file with PASS/FAIL message
+run_test() {
+  compile_and_run $1 && echo "PASS $1" || (echo "FAIL $1"; exit 1)
 }
 
 if [ "$1" == "" ]; then
   for test in $(ls *.java); do
-    compile_and_run $test
+    run_test $test
   done
 else
-  compile_and_run $1.java
+  run_test $1.java
 fi
