Add examples, a java file runner, and general cleanup.

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -2,24 +2,13 @@
 set -e
 cd "`dirname \"$0\"`/.."
 
-mvn package
+./script/build
 
 cd test
 
-compile_and_run() {
-  base_name=`basename -s .java $1`
-  if [[ $string == *"_"* ]]; then
-    cap_base_name=`echo $base_name | ruby -e "puts gets.split(/_/).map(&:capitalize).join"`
-  else
-    cap_base_name=$base_name
-  fi
-  javac -classpath .:"../target/swagger-java-client-1.0.0.jar" $cap_base_name.java
-  java -classpath .:"../target/swagger-java-client-1.0.0.jar":"../target/lib/*" $cap_base_name
-}
-
 # runs a test file with PASS/FAIL message
 run_test() {
-  compile_and_run $1 && echo "PASS $1" || (echo "FAIL $1"; exit 1)
+  ../script/run_java_file $PWD/$1 && echo "PASS $1" || (echo "FAIL $1"; exit 1)
 }
 
 if [ "$1" == "" ]; then
